---
- hosts: '{{ target }}'
  strategy: free
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
     - raw: sudo apt-get update && sudo apt-get -y install python
  roles:
    - { role: initialize_system }
