---
- hosts: '{{ target }}'
  strategy: free
  become: yes
  become_user: root
  gather_facts: yes
  pre_tasks:
     - raw: sudo apt-get update && sudo apt-get -y install python3-pip zstd git gnupg
  roles:
    - { role: initialize_system }

- hosts: '{{ target }}'
  strategy: free
  become: yes
  become_user: root
  vars_files:
    - stage_vars/{{ name }}/{{ stage }}/vars.yml
    - stage_vars/{{ name }}/{{ stage }}/vault.yml
  roles:
    - { role: hyperion, when: setup_hyperion | bool }
    - { role: certbot, when: set_certbot | bool }