---
- name: Preparing bin package
  include_tasks: prebuilt/bin.yml
  when: bin_package | bool

- name: Preparing apt package
  include_tasks:
    file: prebuilt/apt-package.yml
    apply:
      become: yes
      become_user: root
  when: apt_package | bool
