---
- name: Install unzip
  apt:
    name: unzip
  become: yes
  become_user: root

- name: Register snapshot URL
  shell: echo {{ snapshot_base_url }}/{{ snapshot_file }}
  args: 
    executable: /bin/bash
  register: snapshot_url

- name: Downloading latest {{ name }} snapshot from {{ snapshot_provider }}
  get_url:
    url: '{{ snapshot_url.stdout }}'
    dest: '{{ working_dir }}/snapshots/'
    force: yes

- name: Delete nodeos state to prepare snapshot use
  file:
    path: '{{ working_dir }}/deploy/data/state'
    state: absent

- name: Register snapshot file
  shell: "ls -t {{ working_dir }}/snapshots/*.bin | head -n1"
  args:
    executable: /bin/bash
  register: snapshot_bin
